### ISSUE TITLE
ExpenseView를 제출할 수 있을 정도로 수정합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#104]
## 👀 개요
- ExpenseView를 제출할 수 있을 정도로 수정합니다.

## 📝 TODO
- [x] 탭뷰 바운스 수정
- [x] 와이파이 -> 아이콘으로 수정
- [x] 국기 나라 / 금액 합 -> 하이파이 보고 수정
- [x] 결제수단 숫자 -> 카드 현금
- [x] 화폐단위 표시하기
- [x] 전체 지출 여행 선택 모달 연결 확인하기
