### ISSUE TITLE
문자열 분류 메서드(1) - 금액, 단위 등 단어의 범주를 분류합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#11]
## 👀 개요
- 스피치 프레임워크에서 얻은 스트링을 처음으로 다루는 메서드를 만듭니다.
- 부정확한 숫자 인식을 보정하고 내역/금액/단위/지불방식을 구분하는 메서드를 만듭니다.

## 📝 TODO
- [x] 지불방식 정보 분리하기
- [x] 단위 분리하기
- [x] 금액 표현 보정하고 분리하기
- [x] RecordViewModel에 메서드 형태로 넣기
