### ISSUE TITLE
TestFlight 제출을 위한 수정작업을 반영합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#110]
## 👀 개요
- TestFlight 제출을 위한 수정작업을 반영합니다.

## 📝 TODO
- [x] 기본 이미지 추가
- [x] TravelListView 정렬 수정
- [x] 번들 id 변경
- [ ] fastlane으로 제출해보기
- [x] 앱이름 설정 - 노마드월렛
- [x] 아이콘 넣기
- [x] 다크모드 없애기
- [x] 가로모드 막기
- [x] 녹음 허용 경고창 수정
- [x] 암호화 여부 plist 입력하기
