### ISSUE TITLE
위치 정보 API를 연결합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#127]
## 👀 개요
- 위치 정보 API를 RecordView에서 사용할 수 있게 연결합니다.

## 📝 TODO
- [x] 위치 정보 API 공부
- [x] 적절한 API를 선택 후 기능 테스트
- [x] Country와 Location에 각각 어떤 부분까지 저장할 것인지, 외국 주소 형식을 보고 판단
- [x] 위치 정보를 받아오는 함수를 호출하면 앱이 멈추는 문제 해결 중...
- [x] Record 관련 View에 연결
