### ISSUE TITLE
ManualRecordViewModel을 수정합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#131]
## 👀 개요
- ManualRecordViewModel을 수정하고 완성합니다.

## 📝 TODO
- [x] getLocation()의 동작을 의도에 맞게 수정하기
- [x] 초기화할 때 RecordViewModel로부터 녹음 파일의 URL 받아오기
- [x] 지출 금액을 Double로 입력받았을 때 TextField를 비우면 비우기 직전 값이 여전히 남아있는 문제 해결해보고, 해결되면 Double로 대체하기(String을 유지하기로 했다. 대신 didSet에 약간의 필터를 더했다.)
- [x] 금액에 적은 숫자의 소숫점 셋째 이하 날리기
- [x] 위치 정보를 location 엔터티에 저장할 때 문자열 앞부분의 나라 이름은 제외하기
