### ISSUE TITLE
ManualRecordView 지출 장소를 구현합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#132]
## 👀 개요
- ManualRecordView의 지출 위치 수정 기능을 구현합니다.

## 📝 TODO
- [x] 지출 위치의 국기 그림 연동하기
- [x] 지출 위치 수정 버튼 활성화하기(모달)
- [x] 기본 위치 값 일본 관련 내용 삭제하기
