### ISSUE TITLE
환율API를 적용합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#134]
## 👀 개요
- 환율 계산이 필요한 곳에, 환율 API를 적용합니다.

## 📝 TODO
- [x] 환율 API 문서 읽기 (ExchangeRate-API)
- [x] 데이터 구조 생각하기 (화폐 enum을 생성, 각 case(화폐)의 computed property로 환율 저장하기, 하루에 한 번 업데이트 하기)
- [x] 샘플 프로젝트에서 테스트 해보기
- [x] 현재 프로젝트에 적용하기
