### ISSUE TITLE
특정 뷰로 이동할 수 있는 방법을 모색합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#135]
## 👀 개요
- 특정 뷰로 이동할 수 있는 방법을 모색합니다.

## 📝 TODO
- [x] CompleteAddTravelView에서 기록하기 뷰로 이동하기
- [x] TravelDetailView에서 ExpenseView로 이동하기
- [x] MainViewModel을 만들고 필요한 기능을 추가합니다.
- [x] MainViewModel에서 여행 (ex: 방금 만든 여행) 을 알 수 있도록 합니다.
