### ISSUE TITLE
ManualRecordView를 어느 정도 완성합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#142]
## 👀 개요
- ManualRecordView를 어느 정도 완성합니다.
- 녹음 기능은 후순위로 생각하고 이 이슈에서는 구현하지 않습니다.
- 한국, 일본, 베트남 화폐에 한해 소숫점 입력이 안 되게 하는 제한은 국가 리스트 관리가 정리되면 천천히 적용하려고 합니다. 이 이슈에서는 구현하지 않습니다.

## 📝 TODO
- [x] 한화로 계산된 작은 괄호 안의 금액에 쉼표 넣기
- [x] 지출 장소 수정한 다음부터는 상세주소 TextField로 해서 수정 가능하게 하기
- [x] 결제 인원 버튼을 여러 행에 걸쳐 보여주고 한 행에 세 명씩 배치하기
- [x] 결제 인원의 플러스 버튼 없애기
- [x] 5초 + 3초 후 자동 저장 타이머와 화면 표현 구현하기(조작 있으면 타이머 없애기)
- [x] 커스텀으로 구현된 네비게이션 바를 기본 코드로 바꿔보기
- [x] 뒤로가기 누르면 경고창 띄우기
- [x] 음성으로 소숫점 뒤 자리 없는 금액을 입력했을 때 ManualRecordView에서 불필요한 '.0'이 붙는 문제 해결
