### ISSUE TITLE
RecordViewModel과 RecordView를 개선합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#146]
## 👀 개요
- RecordViewModel의 divideVoiceSentence()를 개선합니다.
- RecordView 임시 기록 플로우를 개선합니다.
- RecordView 녹음 버튼 동작의 안정성을 개선합니다.
- RecordView 금액 표시에 쉼표를 넣습니다.

## 📝 TODO
- RecordViewModel
- [x] divideVoiceSentence()에서 소숫점 뒤의 셋째 자리 이하 없애기
- [x] 문장이 비어버리면 이후의 변화를 다른 문자열에 담아서 voiceSentence에는 결국 누적하기(말하고 조금 늦게 녹음 버튼에서 손을 떼었을 때 모든 정보가 없어져버리는 문제 해결, 말을 멈추면 글이 사라지는 문제 해결)
- RecordView
- [x] 임시 기록을 하려고 할 때 여행 생성 권유하는 모달 띄우기
- [x] 모달에서 임시 기록하기 누르면 여행 이름을 '-'에서 '임시 기록’으로 바꾸기
- [x] 금액에 쉼표 넣기
