### ISSUE TITLE
여행 선택 모달을 약간 수정합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#151]
## 👀 개요
- 여행 선택 모달을 약간 수정합니다.

## 📝 TODO
- [x] Expense에서 사용하는 모달의 이름 바꾸기
- [x] 여행 선택 모달 이미지 위에 어두운 그래디언트 넣기
- [x] 체크 버튼 위치 미세하게 다른 것 하이파이처럼 조정하기
