### ISSUE TITLE
TravelListView을 수정합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#156]
## 👀 개요
- TravelListView에서 빠져있는 기능을 추가하고, 하이파이를 반영합니다.

## 📝 TODO
- [x] 임시기록 뷰 연결
- [x] 지난여행, 다가오는 여행 UI 수정
- [x] 진행중인 여행에 국기 이미지 안뜸 처리
- [x] 탭뷰 수정
- [x] 참여자에 me 안뜸
- [x] 지난여행 / 다가오는 여행에서 page가 넘어갈 때 뷰위치 동일하게 수정
