### ISSUE TITLE
InterimRecordView를 구현합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#157]
## 👀 개요
- InterimRecordView를 구현합니다. (세상에마상에 이런 뷰가 있었다니....)

## 📝 TODO
- [ ] 임시기록 뷰와 연결
- [ ] 지출 선택 페이지 구현
- [ ] 캘린더 풀모달
- [ ] 여행 완료 풀모달
