### ISSUE TITLE
Date 문제를 다루는 핸들러를 만듭니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#159]
## 👀 개요
- 현재 코드에서 여행의 시작 날짜, 끝 날짜, 지출 일시를 Date()로 저장하고 있습니다.
- 하지만 Date는 절대적인 기준의 시각이어서 정보를 기록한 장소와 열람하는 장소의 시간대가 다를 때 보여지는 숫자가 달라질 수 있습니다.
	- 예컨대, 캘리포니아에서 오전 9시에 지출했다고 기록하고서 한국으로 와서 지출 기록을 열람하면 그 다음날 오전 2시에 지출했다고 보입니다. 지출했을 때 한국 시각이 그랬기 때문입니다.
	- 추가로, 사용자는 여행 시작 날짜의 0시부터 여행 끝 날짜의 23시 59분 59초까지를 '여행 중'이라고 생각하지만 여행을 생성한 장소와 시간대가 다른 장소에서 앱을 사용하면 저장된 여행의 startDate와 endDate가 자정에서 시차만큼 어긋나게 되어 '여행 중'의 기준이 사용자의 생각과 달라집니다.
- 이를 해결하기 위해서, 저장된 Date 값을 지구상 어디에서 보아도 같은 값으로 보이게 해야 합니다.
	- 간단하게는 시각을 Int나 String으로 저장하면 되겠지만, 일단은 우리의 코어 데이터 구조에서 Date를 사용하고 있으니 Date를 활용해보려고 합니다.
	- Expense
		- 값을 보일 때의 문제에 대한 해결 계획: 저장된 Date 값은 사용자의 이동에 따라 자동으로 바꿀 수 없으므로 이것을 화면에 일관되게 표시하려면 저장된 Date를 한국 시각으로 해석했을 때 보이는 월일시분 숫자가 화면에 보이도록 사용자의 장소에 맞는 시차 조정을 먼저 하고 화면에 보여주어야 합니다.
		- 저장할 때의 문제에 대한 해결 계획: 어떤 나라에서 지출 기록을 하더라도 기록할 때의 그 나라의 시간이 그대로 보여지길 바라므로, 예컨대 프랑스에서 오후 3시에 지출했다면 저장할 때 같은 날짜 한국 오후 3시의 Date로 저장해야 합니다.
	- Travel
		- 값을 보일 때의 문제에 대한 해결 계획: 여행 중인지를 판단할 때는 저장된 startDate, endDate와 현재의 Date를 비교하는데, 이때 저장된 startDate, endDate는 한국 기준으로 자정에 가까운 Date여야 합니다. 하지만 현재의 Date는 앱을 사용하는 장소에서의 Date이므로 이대로 비교하면 안 됩니다. startDate와 endDate를 먼저 사용자의 장소에 맞게 시차 조정을 하고서 현재의 Date와 비교해야 합니다.
		- 저장할 때의 문제에 대한 해결 계획: startDate와 endDate는 사용자 장소 기준의 00시, 23시 59분 59초가 아니라 한국 기준이어야 합니다. 사용자 장소 기준으로 구하고서 한국 기준시로 변환한 후에 저장해야 합니다.
- 요약하자면 저장할 때는 현지 오후 3시를 한국 오후 3시로 바꾼 후에 저장하고, 값을 화면에 보일 때는 한국 오후 3시를 현지 오후 3시로 바꾼 후에 보여주어야 합니다.

## 📝 TODO
- [x] DateGapHandler 만들기
- [x] DateGapHandler에서 위치 정보 사용할 수 있게 하기
- [x] 핸들러 안에 현지 오후 3시 Date를 한국 오후 3시 Date로 바꾸는 변환 메서드 convertBeforeSaving(date:)만들기(저장하기 전에 사용)
- [x] 핸들러 안에 한국 오후 3시 Date를 현지 오후 3시 Date로 바꾸는 변환 메서드 convertBeforeShowing(date:)만들기(화면에 보여주기 전에 사용)

**Comment by GYURI-PARK** [comment]
짱...🥹🥹🥹
