### ISSUE TITLE
Curreny 정보를 담은 .csv 파일을 만들고, CurrencyInfo 구조체를 만듭니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#167]
## 👀 개요
- Curreny 정보를 담은 CurrencyList.csv 파일을 만들고, CurrencyInfo 구조체를 만듭니다.
- CurrencyList.csv 파일에는 다음과 같은 정보가 있습니다
    - id: Int
    - isoCodeNm(iso 4217 코드): String
    - koreanNm(한글 화폐명): String
    - symbol(기호): String
    - 환율: -> ExchangeRateHandler에서 [iso4217코드 문자열: 환율] 형태로 userDefault로 저장하고 있음.

- CurrencyInfo 구조체는 다음과 같을 예정입니다.
```
struct CurrencyInfo {
    let isoCodeNm: String
    let koreanNm: String
    let symbol: String
}
```

- CountryList.csv 파일에는 다음과 같은 정보를 추가할 예정입니다. @GYURI-PARK(기존 작성자), @oliver-or-not(사용자) 의 확인이 필요합니다.
    - relatedCurrencyArray: [CurrencyInfo.isoCodeNm]
    - 해당 국가가 사용하는 CurrencyInfo.isoCodeNm들의 배열입니다.
    - [CurrencyInfo]를 사용하지 않은 이유는, .csv 파일에 구조체 정보를 담는 방법을 찾아내지 못 했기 떄문입니다.
    - [CurrencyInfo.id]를 사용하지 않은 이유는, 상수 값을 입력하면 헷갈리기 때문에 csv 파일 관리가 어려워지기 때문입니다.

## 📝 TODO
- [x] @GYURI-PARK 작성한 형식을 참고하기
- [x] CurrencyList.csv 생성하기
- [x] CurrencyInfo 구조체 생성하기
- [x] CurrencyInfoModel 생성하기 
- [x] CountryList.csv에 [주요 화폐] 정보 추가
- [x] CountryInfo 구조체에 relatedCurrencyArray 프로퍼티 추가
- [x] CountryInfoModel에 relatedCurrencyArray로 인한 변경 사항 추가
- [x] 실제로 사용하는 뷰에서 테스트 해보기 (Currency만)
