### ISSUE TITLE
정산 내역 페이지 viewModel을 구현합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#17]
## 👀 개요
- 정산 내역 페이지 viewModel을 구현합니다.

## 📝 TODO
- [x] Core Data를 활용할 수 있도록 viewContext 함수를 작성
- [x] 그밖에 필요한 함수를 작성
- [x] 기능을 테스트해보기 위한 최소한의 view를 그림
- [x] TodayExpenseView
- [x] TodayExpenseDetailView
- [x] AllExpenseView
- [x] AllExpenseDetailView
