### ISSUE TITLE
Expense 관련 뷰에 MainViewModel를 적용합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#171]
## 👀 개요
- Expense 관련 뷰에 MainViewModel를 적용합니다.
- 예상: 2시간
- 실제: 3시간 20분

## 📝 TODO
- [x] Expense에서만 사용하는 별도의 변수인 selectedTravelInExpense가 필요한지 고민
    - findCurrentTravel()을 TravelListView의 onAppear로 옮기면, ExpenseView에서 selectedTravel을 변경해도, 앱을 켤 때 다시 현재 여행이 선택되기 때문에, 별도 변수를 생성하지 않아도 괜찮을 듯?
- [x] expenseViewModel.selectedTravel을 mainVM.selectedTravel로 변경
- [x] 연계 되어서 발생하는 로직 문제 해결
- [x] TravelChoiceModal로 A여행에서 B여행 선택 후에, B여행의 AllExpenseDetailVeiw에 들어갔다가 나오면, A여행으로 이동하는 문제를 해결
