### ISSUE TITLE
CompletetTravelView의 여행 이름 수정사항을 반영합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#177]
## 👀 개요
- CompletetTravelView의 여행 이름 수정사항을 반영합니다.

## 📝 TODO
- [x] 기본 이름 변경
- [x] 텍스트 필드가 아닌 펜을 버튼으로 바꾸기
- [x] 버튼 색상 변경
