### ISSUE TITLE
SettingView를 구현합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#179]
## 👀 개요
- SettingView를 구현합니다.
- 예상: 2시간
- 소요: 약 6시간 !

## 📝 TODO
- [x] SettingView의 gui를 구현합니다.
- [x] SettingView의 기능을 구현합니다.
- [x] 데이터 삭제가 가능한 건지 검색하고, 구경해 봅니다.
- [x] 기획팀과의 합의 지점을 찾습니다.
    - [x] 기본 리스트 컴포넌트의 Section 수직 padding 조절 불가 문제: Stack으로 그릴 것인지 ?
    - [x] 알림 설정: 현재는 알림 허용이 없기에, 설정창도 없음
    - [ ] 약관 및 정책: 내용 없음 -> 추가 예정
    - [ ] 개인정보취급방침: 내용 없음 -> 추가 예정
    - [x] ~~위치 허용 Toggle로~~
    - [x] ~~마이크 허용 Toggle로~~
