### ISSUE TITLE
문자열 분류 메서드 (2) - 구매내역을 카테고리별로 분류합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#18]
## 👀 개요
- CreateML과 한국어 말뭉치 데이터셋을 이용해서 구매내역의 카테고리를 분류하는 메서드를 만듭니다.

## 📝 TODO
- [x] CreateML로 머신 러닝 모델 생성하기
- [x] 분류의 기준 정하기
- [x] 한국어 말뭉치 데이터셋으로 모델 학습시키기
- [x] 학습시킨 머신 러닝 모델을 프로젝트에 추가하기
- [x] RecordViewModel에 메서드 형태로 정리해넣기

**Comment by oliver-or-not** [comment]
중간 기록: 수동으로 약 170개의 단어와 그 분류 정보를 학습 데이터로 입력하고 CreateML로 학습시킨 모델을 프로젝트에 적용해본 결과 동작함을 확인했습니다. 하지만 학습 데이터를 늘려서 모델의 정확도를 더 높일 필요가 있습니다. 모델 개선은 따로 이슈를 만들어서 장기적으로 시간을 투자할 생각입니다.
