### ISSUE TITLE
녹음 파일을 코어 데이터에 저장합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#190]
## 👀 개요
- 녹음 파일을 저장하고 사용할 수 있게 합니다.

## 📝 TODO
- [x] 녹음 파일을 코어 데이터에 저장합니다.
- [x] 코어 데이터에 저장된 녹음 파일을 불러와 재생하는 방법을 구현해봅니다.
- [x] 파일 매니저를 통해 저장한 녹음 파일이 적절한 타이밍에 삭제되게 합니다.
