### ISSUE TITLE
TravelDetailView의 변경된 UI를 적용합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#192]
## 👀 개요
- TravelDetailView의 변경된 UI를 적용합니다.

## 📝 TODO
- [x] 순서 배치 다시하기
- [x] 함께하는 사람 UI 수정
- [x] 여행 국가 UI 수정
- [x] 위에 여행 중 / 지난 여행 / 다가오는 여행 띄우기
