### ISSUE TITLE
ManualRecordView 소소한 수정을 합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#196]
## 👀 개요
- ManualRecordView 몇 가지를 수정합니다.

## 📝 TODO
- [x] ManualRecordView 저장 버튼이 갑자기 너무 아래로 옮겨져서 위치 조정
- [x] ManualRecordViewModel의 save() 메서드 안에 Currency 이뉴머레이션을 아직 사용하는 코드 있는데 그것 수정
- [x] ManualRecordView에서 지출 저장하고서 불필요한 오디오 파일 삭제하기
