### ISSUE TITLE
Speech 프레임워크를 이용해 STT 기능 구현합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#20]
## 👀 개요
- Speech 프레임워크를 이용해 STT 기능 구현합니다.

## 📝 TODO
- [x] Speech 프레임워크 공부
- [x] MVVM에 맞춰 기능개발
- [x] LongPressGesture 공부
- [x] Long Press Gesture 기능 적용
