### ISSUE TITLE
여행 선택 모달과 탭뷰에 hi-fi를 반영합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#203]
## 👀 개요
- 뷰에 미반영된 Hi-fi를 일부 반영합니다.

## 📝 TODO
- [x] 앱 실행하고 처음 보이는 화면을 지출 기록 탭으로 합니다.
- [x] 지출 위치 상세 입력 창 플레이스홀더를 바꿉니다.
- [x] 여행 선택 모달의 sortRule을 기능명세처럼 바꿉니다.
