### ISSUE TITLE
뷰 init 없애기

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#204]
## 👀 개요
- 뷰 init을 없앱니다. 안정적인 뷰 운용을 위해.

## 📝 TODO
- [x] ManualRecordViewModel init을 없앱니다.
- [x] Expense 관련 뷰 init을 없앱니다.
- [x] 여러 모달의 init을 없앱니다.
