### ISSUE TITLE
여행 생성 시 Datehandler를 적용합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#209]
## 👀 개요
- 여행 생성 시 DateGaphandler를 적용합니다.

## 📝 TODO
- [x] convertBeforeShowing을 모두 적용합니다.
- [x] TravelListView 진행 중인 여행
- [x] TravelListView 지난 여행
- [x] TravelListView 다가오는 여행
- [x] TravelDetailView의 시작일 출발일
- [x] InterimRecordView의 DefaultTravel
- [x] InterimRecordView 진행 중
- [x] InterimRecordView 지난
- [x] InterimRecordView 다가오는
- [x] convertBeforeSaving을 모두 적용합니다.
