### ISSUE TITLE
여행 선택 모달의 오류들을 수정합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#215]
## 👀 개요
- 여행 선택 모달의 오류들을 수정합니다.

<img width="20%" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team11-UMM/assets/93391058/f5cf17e3-806e-4201-8d7c-8f3ec74c71f5">

## 📝 TODO
- [ ] 배경이미지가 없는 여행들은 날짜와 국기가 뜨지않고 있어요.
- [ ] 배경이미지가 없는 여행들은 선택도 되지 않아요.
- [ ] 만든적없는 이름이 "-"인 여행이 생성되어 있습니다.
- [ ] 임시기록들이 매우 많이 생성되어있어요🥹

**Comment by oliver-or-not** [comment]
😥😥😥
