### ISSUE TITLE
Travel관련 뷰들의 HIFI를 반영합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#216]
## 👀 개요
- Travel관련 뷰들의 HIFI를 반영합니다.

## 📝 TODO
- [x] 캘린더 전체기간 표시 수정
- [x] 삭제 시 경고창 수정
- [x] 여행이 여러번 저장되는 코드 수정
- [x] DateGapHandler 수정 사항 반영
- [x] TravelListView의 인덱스 수정
