### ISSUE TITLE
Expense 관련 뷰와 ManualRecordInExpenseView를 연결합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#218]
## 👀 개요
- Expense 관련 뷰와 ManualRecordInExpenseView를 연결합니다.
- onAppear 했을 때 데이터는 잘 넘어가는 것이 확인되었지만, 과정에서 init 되어 화면이 초기화 됩니다.
- 녹음 파일의 정상 작동 여부는 아직 미지수 입니다.

## 📝 TODO
- [x] TodayExpenseDetailView: ManualRecordInExpenseView 연결
- [x] TodayExpenseDetailView: 데이터 조회, 수정, 저장 구현
- [x] AllExpenseDetailView: ManualRecordInExpenseView 연결
- [x] AllExpenseDetailView: 데이터 조회, 수정, 저장 구현
