### ISSUE TITLE
각종 에러를 해결합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#219]
## 👀 개요
- QA 과정에서 제기된 에러를 해결합니다.

## 📝 TODO
- [x] Date Range로 앱 크래시 되는 에러 수정
- [x] Expense: TravelChoiceView 옆에 “가계부” 추가
- [ ] TravelChoiceModal이 "열리면" 화면 다시 그려지는 문제
- [ ] ManualRecordInExpenseView에서 3자리 마다 쉼표X
- [x] DetailView에서 항목 빨간 글씨
- [x] ManualRecordInExpenseView 저장하기 버튼
- [x] selectedTravel과 selectedTravelInExpense 연결하기
- [x] 처음 화면 떴을 때, 환율 API 정보 못 가져옴. 왜냐하면 초기 화면이 RrecordView로 갔기 때문에.
