### ISSUE TITLE
여행 참여자들을 추가하는 기능을 수정합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#222]
## 👀 개요
- 여행 참여자들을 추가하는 기능에서의 오류들을 수정합니다.

## 📝 TODO
- [x] TravelListview 여행 참여자가 여러 명일 경우 첫번째 추가하는 참여자는 뷰에 나타나지 않습니다.
- [x] CompleteView에서 Default 여행 제목 받아오기
- [x] TravelDetailView : 참여자가 제대로 나타나지 않습니다.
- [x] TravelListView에서 참여자가 없을 경우 me를 표시해주기 위해 빈 스트링 대신 "me"를 넣었더니 RecordView에서 me가 생성되는데 이 부분 수정할게요
