### ISSUE TITLE
임시 기록에 관한 몇 가지를 수정합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#227]
## 👀 개요
- 임시 기록에 관한 몇 가지를 수정합니다.

## 📝 TODO
- [x] 임시 기록이 "-"로 보여지는 곳들을 전부 "임시 기록"으로 바꿉니다.
- [x] 임시 기록 글자는 gray400으로 약간 흐리게 합니다.
- [x] 임시 기록을 권유하는 모달의 버튼의 좌우를 바꿉니다. 단 배경색은 왼쪽이 회색이게 그대로.
