### ISSUE TITLE
TravelView 수정사항을 반영합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#228]
## 👀 개요
- TravelView 수정사항을 반영합니다.

## 📝 TODO

1차 수정
- [x] InterimRecordView 지난/다가오는 여행 TabBar title 수정
- [x] TravelListView, TravelDetailView 디데이 수정
- [x] 진행 중인 여행에서만 디데이 보이도록 수정
- [x] TravelDetailView 여행 국가가 없어도 너비가 유지되도록 수정

2차 수정
- [x] TravelListView 오류 수정

3차 수정
- [x] InterimRecordView 임시기록 정렬 (최근 기록이 앞에 오도록)
- [x] 여러 나라 여행 할 때 정렬 순서 추가
- [x] Default 여행은 보이지 않도록 수정
