### ISSUE TITLE
ManualRecordInExpenseView에서 저장하기와 백 버튼 로직을 만듭니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#230]
## 👀 개요
- ManualRecordInExpenseView에서 저장하기와 백 버튼 로직을 만듭니다.

## 📝 TODO
- [x] 데이터를 수정하지 않으면 저장하기 버튼이 사라지고, 백 버튼이 알러트를 호출하지 않게 만듭니다.
- [x] 데이터를 수정하면 저장하기 버튼이 나타나고, 백 버튼이 알러트를 호출합니다.
- [x] 데이터를 수정했다가 원본값으로 돌아오면 첫 번째 케이스를 적용합니다.
