### ISSUE TITLE
제출 전 최종 수정사항들을 반영합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#249]
## 👀 개요
- 제출 전 최종 수정사항들을 반영합니다.

## 📝 TODO
- [x] InterimRecordView가 비어있을 때 문구 수정
- [x] AllExpenseVIew 빨간 글씨 -> 검정 글씨로
- [x] 더미 데이터 삭제
- [x] InterimRecordView에서 임시 기록 삭제
- [x] InterimRecordView에서 폰트 크기 변경
- [x] ExpenseTabBar 양쪽 패딩 제거
- [x] Expense 탭바 배경 제거
