### ISSUE TITLE
SwiftLint 제한을 약화시킵니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#25]
## 👀 개요
- SwiftLint의 몇 가지 제약을 약화시킵니다.

## 📝 TODO
- [x] 빈 줄 입력할 수 있게 하기
- [x] 함수 길이 제한 삭제
- [x] 함수 복잡도(Cyclomatic complexity) 제한 삭제
