### ISSUE TITLE
출시 후 수정해야 하는 Expense 관련 버그

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#265]
## 👀 개요
- 출시 후 수정해야 하는 Expense 관련 버그를 수정합니다.

## 📝 TODO
- [ ] SettingView에서 제대로 된 link를 제공하도록 수정
- [ ] 최초 앱 실행 때 RecordView에서 여행을 선택하지 않으면, ExpenseView에서 여행이 선택되지 않음
- [ ] ExpenseView에서 여행을 선택하면, 여행의 범위가 현재 날짜를 벗어났을 때, 여행의 시작일로 DatePicker가 변경되도록
- [ ] 환율 정보를 제대로 받아오지 않는 문제
- [ ] TravelChoiceModal이 "열리면" 화면 다시 그려지는 문제
- [ ] ManualRecordInExpenseView에서 3자리 마다 쉼표X
- [ ] ManualRecordInExpenseView에서 participantArray가 제대로 동작하지 않는 문제
- [ ] GUI를 전체적으로 피그마에 맞게 수정
- [ ] expense 관련 모든 뷰에 line limit 설정하기
