### ISSUE TITLE
Travel View와 관련된 간단한 UI를 수정합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#273]
## 👀 개요
- Travel View와 관련된 간단한 UI를 수정합니다.

## 📝 TODO
- [x] 진행 중인 여행 앨범과 미분류된 지출내역 칸 사이의 padding이 피그마보다 좁아요 -> 넓혀주세요!
- [x] 캘린더가 6주인 달에 마지막 주에 있는 숫자들과 캘린더 테두리 선까지의 거리가 너무 가까워요! 피그마 참고 !
- [x] 2인 여행 시 ㅇㅇ 와의 여행 → ㅇㅇ 님과의 여행
- [x] 인원 유무 선택 시 라디오 버튼(원 모양 버튼)의 왼쪽 padding이 피그마보다 좁아요!
- [x] 참여인원 이름 길이 제한이 없다. 한글 5글자 영어 8글자
- [x] 여행 이름 제한이 없다. 한글 8글자 영어 12글자
- [x] TravelDetailView 패딩값 수정 (32)
