### ISSUE TITLE
selectedTravel, selectedTravelInExpense 정리

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#283]
## 👀 개요
- 아래의 기준을 따릅니다:
- 용어 정리
	- str: selectedTravel
	- ste: selectedTravelInExpense
- 앱 켰을 때 - 임시 기록 여행 외에는 여행이 없는 경우
	- str -> 임시 기록 여행
	- ste -> 임시 기록 여행
- 앱 켰을 때 - 임시 기록 여행 외에 여행이 있으나 현재 진행 중인 여행이 없는 경우
	- str -> 임시 기록 여행
	- ste -> travelModalSortRule에서 가장 빠른 여행
- 앱 켰을 때 - 현재 진행 중인 여행이 있는 경우
	- str -> 현재 진행 중인 여행 중에 lastUpdate가 가장 최근인 여행
	- ste -> 현재 진행 중인 여행 중에 lastUpdate가 가장 최근인 여행
- 지출 기록 탭에서 선택 - 임시 기록 여행을 선택한 경우 - 임시 기록 여행 외에 여행이 있으나 현재 진행 중인 여행이 없는 경우
	- str -> 임시 기록 여행
	- ste -> (임시 기록이 아닌 기존의 값 유지) (didSet에 의해)
- 지출 기록 탭에서 선택 - 임시 기록 여행을 선택한 경우 - 현재 진행 중인 여행이 있는 경우
	- str -> 임시 기록 여행
	- ste -> (임시 기록이 아닌 기존의 값 유지) (didSet에 의해)
- 지출 기록 탭에서 선택 - 임시 아닌 여행을 선택한 경우
	- str -> 선택한 여행
	- ste -> 선택한 여행 (didSet에 의해)
- 가계부 탭에서 선택 - 임시 아닌 여행을 선택한 경우
	- str -> 선택한 여행 (didSet에 의해)
	- ste -> 선택한 여행
- 여행 생성
	-  str -> 생성한 여행
	- ste -> 생성한 여행 (didSet에 의해)
- 여행 삭제
	- str, ste 둘 중 하나 이상 삭제된 여행을 선택하고 있었던 경우에 앱 새로 켰을 때의 기준대로 str, ste 값 변경
- ste는 str의 didSet으로 수정됩니다. str이 임시 기록 여행이 아닌 경우에 str을 따라하고 str이 임시 기록 여행인 경우에는 따라하지 않고 값을 유지합니다.
- str은 ste의 didSet으로 수정됩니다. ste의 값을 따라합니다.

## 📝 TODO
- [x] 앱 켰을 때 selectedTravelInExpense를 findCurrentTravel() 아닌 다른 기준으로 초기화
- [x] 여행 생성할 때 str(따라서 didSet으로 ste까지 같이) 업데이트
- [x] 여행 삭제할 때 str, ste 값 기준에 맞게 변경
