### ISSUE TITLE
수정

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#286]
## 👀 개요
- 수정할 것들을 수정합니다.

## 📝 TODO
- [x] 녹음 버튼 눌러야 여행 생성 권유 모달이 뜨게 하기
- [x] 임시 기록 여행 외에 아무 여행도 없을 때만 여행 생성 권유 모달이 뜨게 하기
- [x] 쉐브론 아닌 텍스트 영역 터치해도 수정 기능 시작하기
- [x] ManualRecordView 위치를 화면에 표시하지 않는 문제 수정
- [x] 여행 고르는 빨간 캡슐에 lineLimit 넣기(RecordView)
- [x] ManualRecordView의 금액 표시에서 줄임 표시 없애고 차라리 축소를 허용하기
- [x] ManualRecordView의 onAppear에서 필요한 초깃값만 주기
- [x] ManualRecordView의 DatePicker에서 여행 기간 제한 없애기
- [x] 없어야 하는 소리가 재생되는 문제 해결
