### ISSUE TITLE
ManualRecordInExpenseView에 몇 가지 적용 사항을 적용합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#290]
## 👀 개요
- ManualRecordInExpenseView에 몇 가지 적용 사항을 적용합니다.

## 📝 TODO
- [x] ManualRecordInExpenseView와 ManualRecordView의 코드를 동기화 합니다.
- [x] AllExpenseDetailView에서 마지막 날에는 하단 divider 삭제
- [x] AllDetailView 백 버튼에 이전 국가 추가
