### ISSUE TITLE
QA에 따른 긴급 수정 사항을 적용합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#304]
## 👀 개요
- QA에 따른 긴급 수정 사항을 적용합니다.

## 📝 TODO
- [x] trashCanGray의 저장된 파일 이름을 영어로 변경
- [x] SettingView가 화면을 다 가리게 변경합니다. TabView가 사라졌다가 뜨면 문제를 해결하면 더 좋습니다.
- [x] 다른 기기에서 customDatePicker가 안 눌릴 때가 있는지 점검합니다.
- [x] participantArray의 저장 문제를 해결합니다.
