### ISSUE TITLE
이름을 입력하지 않았을 때 participantArr에서 제외합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#308]
## 👀 개요
- 이름을 입력하지 않았을 때 participantArr에서 제외합니다.

## 📝 TODO
- [x] 이름을 입력하지 않았을 때 participantArr에서 제외
- [x] 여러 명에서 정산하기 눌렀는데 이름을 아무도 입력하지 않았을 때 화면이 멈추는 오류 해결하기
- [x] 나 + 중복 이름 제거 처리
