### ISSUE TITLE
1.1.2 이후 QA 변경 사항을 적용합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#323]
## 👀 개요
- 1.1.2 업데이트 이후 QA 변경 사항을 적용합니다.

## 📝 TODO 
(⭐️는 중요도를 의미합니다.)
- [x] customeDatePicker를 기본 UI로 변경하기 ⭐️⭐️⭐️⭐️
- [x] 스크롤 영역이 늘어날 때 탭바 색이 회색으로 바뀌는 문제를 흰색으로 수정 ⭐️
- [x] TodayExpenseView: 최신 업데이트 된 국가 순으로 정렬 ⭐️⭐️
- [x] 로그인 없이 iCloud에 저장할 수 있는지 ⭐️⭐️⭐️
- [x] 기능 명세를 받아 font를 fixedSize로 수정하기 ⭐️⭐️⭐️
- [x] 텍스트 필드에 minimumScaleFactor 적용하기 ⭐️⭐️⭐️
- [x] @oliver-or-not travelChoice의 위치를 조절합니다. + SE3를 대응합니다. ⭐️⭐️⭐️⭐️
- [x] @oliver-or-not 추가된 선물 카테고리를 적용합니다. ⭐️⭐️⭐️⭐️
- [x] 여행 기간 외 기록된 지출 기록을 전/중/후 나눠서 "여행 전" / "Day1~DayN" / "여행 후" 로 보여주기 ⭐️⭐️⭐️
- [x] AllExpenseDetailView: 지출 기록을 날짜의 내림차순, 오름차순으로 정렬하는 버튼 추가하기 ⭐️
