### ISSUE TITLE
1.1.2 이후의 QA를 반영합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#324]
## 👀 개요
- 1.1.2 이후의 QA를 반영합니다.

## 📝 TODO
- [x] ⭐️⭐️⭐️⭐️ TravelDetailView에서 다른 뷰로 넘어갈 때 여행 연결하기 
- [x] 🥕 alert 모달의 tint color 없애기
- [x] 👀 alert 취소 버튼에 손올리고 드래기 시 회색 배경
- [x] ⭐️⭐️ 임시기록 page indicator 위치 조정
- [x] ⭐️⭐️⭐️  임시기록 화폐단위 영어 -> 한글
- [x] 달력 안에 날짜 fixed font로 크기 고정
