### ISSUE TITLE
지출 기록 탭에서 수정할 사항을 수정합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#325]
## 👀 개요
- QA 후 지출 기록 탭에서 수정하기로 한 사항을 수정합니다.

## 📝 TODO
- [x] 위치 정보가 받아와지지 않더라도 최근 기록 위치에 맞게 화폐 적용하기
- [x] 지출 카테고리에 선물 추가 - 이뉴머레이션에 추가
- [x] 지출 카테고리에 선물 추가 - 카테고리 모달에 추가
