### ISSUE TITLE
:bug: 출시 전 마지막 버그를 해결합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#345]
## 👀 개요
- 몇 가지 버그를 해결합니다.

## 📝 TODO
- [x] 여행이 지난 경우에 "여행 후"가 제대로 표시되지 않는 문제를 해결합니다.
- [x] .csv에서 여행 전 후가 제대로 표시되도록 수정합니다.
- [x] 몇 가지 텍스트를 수정합니다.
    - [x] 지출 삭제
    - [x] 공유하기 버튼
- [x] expense.info에 적힌 쉼표를 인식하지 않도록 수정합니다.
- [x] UTType 문제를 해결합니다.
