### ISSUE TITLE
1.2.0 버전의 소소한 수정사항들을 반영합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#348]
## 👀 개요
- 1.2.0 버전의 소소한 수정사항들을 반영합니다.

## 📝 TODO
- [x] TravelDetailView의 국가들 스크롤뷰 처리
- [ ] 지출 순서를 저장하고 국가를 그에 맞게 표시
- [x] 한국 지폐단위가 잘 안뜨는 이슈 해결하기
