### ISSUE TITLE
현재 진행 중인 여행을 결정하는 함수를 구현합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#35]
## 👀 개요
- 현재 진행 중인 여행을 결정하는 함수를 구현

## 📝 TODO
- [ ] 추가적으로 고려할 app flow & data flow 설계
- [ ] 필요한 데이터 구조 변경
- [ ] 함수 구현 및 메인 화면(TravelListView)에 적용
