### ISSUE TITLE
Color와 Font 관련 파일을 추가합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#38]
## 👀 개요
- 색깔을 편하게 쓸 수 있도록 Color와 관련된 파일들을 추가합니다.

## 📝 TODO
- [x] Color Extension 추가
- [x] Color Set 추가
- [x] Font 파일 추가
