### ISSUE TITLE
RecordView를 구현합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#42]
## 👀 개요
- RecordView를 구현합니다.

## 📝 TODO
- [x] 녹음 버튼을 롱 프레스하는 동안 실시간으로 화면에 받아쓰기된 텍스트와 정제된 정보가 보이게 합니다.
- [x] 녹음 버튼을 떼면 CompleteRecordView가 모달로 나오게 합니다.
- [x] 직접 기록 버튼을 누르면 ManualRecordView가 모달로 나오게 합니다.
- [x] 위쪽 여행 선택 버튼을 누르면 여행 선택 반모달이 나오게 합니다.
