### ISSUE TITLE
테스트를 위한 더미 데이터와 몇 가지 정보를 입력합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#53]
## 👀 개요
- 테스트를 위한 더미 데이터와 몇 가지 정보를 입력합니다.

## 📝 TODO
- [x] 탭뷰연결
- [x] 뷰 폴더링
- [x] 이뉴머레이션 모으기
- [x] Travel 몇 개 코어 데이터에 더해주기
- [x] Expense 몇 개 코어 데이터에 추가
- [x] CoreData 수정
- [x] 국가 enum 만들고 케이스 몇 개 추가
- [x] 화폐 enum...
