### ISSUE TITLE
위치 API와 환율 API를 적용합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#56]
## 👀 개요
- 위치 API와 환율 API를 적용

## 📝 TODO
 - [ ] 위치 api 공부
- [ ] 위치 api 적용: CoreData에 저장, 오프라인 환경 고려
- [ ] 환율 api 공부
- [ ] 환율 api 적용: 오프라인 환경 고려
