### ISSUE TITLE
AddMemberView의 기능을 구현합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#58]
## 👀 개요
- AddMemberView에서 함께할 사람들을 설정하면 ViewModel에 저장합니다. (완료 후 Core Date 저장 !)

## 📝 TODO
- [x] AddMemberView 뷰 대애충 그리기
- [x] 정산 필요 없을 경우
- [x] 정산이 필요한 경우
