### ISSUE TITLE
AddTravelView의 추가 수정사항들을 반영합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#60]
## 👀 개요
- AddTravelView의 추가 수정사항들을 반영합니다.

## 📝 TODO
- [ ] 여행 기간 전체 표시
- [x] 달력에 YEAR 값 반영 
- [x] 시작일, 종료일 뷰 수정
