### ISSUE TITLE
완료 시 Core Data에 데이터의 정보를 저장합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#64]
## 👀 개요
- 완료 시 Core Data에 데이터의 정보를 저장합니다.

## 📝 TODO
- [x] Core Data에 정산자 저장
- [x] 출발일, 종료일 저장
- [x] 네비게이션 기능과 버튼 기능 둘다 작동되게 하기
