### ISSUE TITLE
RecordViewModel의 STT 기능의 버그를 해결합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#70]
## 👀 개요
- STT 기능의 버그를 해결합니다.

## 📝 TODO
- [x] STT를 앱 켜고 단 한 번만 할 수 있는 버그를 해결합니다.
- [x] 보라색 에러 메시지를 해결합니다.
- [x] STT 시작할 때의 멈춤 현상을 해결합니다.
- (X) 버그로 동작하지 않았던, 녹음 시작의 진동 효과를 적용합니다. (포기)
