### ISSUE TITLE
RecordView의 AlertView 부분을 완성합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#71]
## 👀 개요
- AlertView를 완성합니다.

## 📝 TODO
- [x] 입력 내용이 부족할 때의 AlertView 외형과 동작을 완성합니다.
- [x] 너무 짧게 녹음했을 때의 AlertView 외형과 동작을 완성합니다.
- [x] '누르는 동안 말하기' 보이게 합니다.
- (X) 블러 효과 적용합니다.
