### ISSUE TITLE
ManualRecordView를 구현합니다.(내부 쇼케이스 전까지의 작업)

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#72]
## 👀 개요
- 수기기록 및 녹음 후 수정을 할 수 있게 ManualRecordView를 구현합니다.
- CompleteRecordView는 hi-fi의 변경으로 사라졌고 ManualRecordView에 통합되었습니다.

## 📝 TODO
- [x] 뷰모델 만들기
- [x] 뷰모델 변수 화면에 보이기
- [x] UI를 통한 수정 기능 구현하기(지출 일시와 지출 위치 제외)
- [x] 코어 데이터 저장 기능 구현하기
