### ISSUE TITLE
CompleteRecordView를 구현합니다.

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#73]
## 👀 개요
- 저장을 할 수 있게 CompleteRecordView를 구현합니다.

## 📝 TODO
- [ ] 코어 데이터 저장 기능 구현하기
- [ ] 특히 녹음 파일 코어 데이터에 저장하기
- [ ] 뷰 완성하기
- [ ] 파일 매니저에 저장되어 있는 녹음 파일들 필요 없어지면 지우기

**Comment by oliver-or-not** [comment]
CompleteRecordView는 사라지고 ManualRecordView에 기능이 통합되었습니다.
