### ISSUE TITLE
Core Data 데이터 모델 초기 구현

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#8]
## 👀 개요
- CoreData Entity, Relationship, 그리고 viewContext를 구현합니다.

## 📝 TODO
- [x] .xcdatamodeld 파일에 entity, relationship 구현하기
- [x] Persistence 파일 추가
- [x] 환경객체로 앱에 추가
