### ISSUE TITLE
TravelChoiceHalfView와 관련된 것의 접근성을 변경합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#83]
## 👀 개요
- TravelChoiceHalfView 관련 기능을 Handler로 변경합니다.
- 해당 View를 RecordView와 ExpenseView에서 사용하고 있습니다. 
- 해당 View가 2개의 ViewModel을 따라야하기 때문에 MVVM을 지킬 수 없기에, 관련 변수와 함수를 어디서나 접근할 수 있도록 변경합니다.
- chosenTravel 값이 뷰마다 다른 것도 어색합니다.

## 📝 TODO
- [x] View 이해 관계자(@oliver-or-not)와 상의한다.

### 📝 TODO(@oliver-or-not)
- [x] 공유될 뷰에 해당하는 프로토콜을 만든다.
- [x] 공유될 뷰에는 독립적인 ObservableObject viewModel과 생성자의 파라미터로 받아오는 givenViewModel 각각을 만든다.
- [x] 공유될 뷰를 사용할 뷰의 뷰모델이 그 프로토콜을 따르도록 한다.
- [x] 적절한 위치에서 사용한다. 

### 📝 TODO(@unboxing96)
- [x] 공유될 뷰를 사용할 뷰의 뷰모델이 그 프로토콜을 따르도록 한다.
- [x] 적절한 위치에서 사용한다.

**Comment by unboxing96** [comment]
감사합니다. 적용해보도록 할게요 !

**Comment by oliver-or-not** [comment]
바인딩으로 해버렸습니다
