### ISSUE TITLE
올리버의 간단한 세션 - CoreML, protocol, 반응형 사이즈 조절

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#88]
## 👀 개요
- 👀👀👀 이번 프로젝트에서 사용된 기술을 공유합니다.

## 📝 TODO
- [ ] 공유할 내용: CoreML로 텍스트 분류하기
- [ ] 공유할 내용: 프로토콜을 이용해서 여러 위치에서 하나의 뷰 사용하기
- [ ] 공유할 내용: 간단한 코드로 화면 크기에 맞게 뷰 사이즈 조절하기(사용할지는 미정)

**Comment by unboxing96** [comment]
우와 ! 기대가 되네요 !
