### ISSUE TITLE
TravelListView의 수정 사항들을 반영합니다.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#91]
## 👀 개요
- TravelListView의 수정 사항들을 반영합니다.

## 📝 TODO
- [x] 스크롤뷰의 page indicator 수정
- [x] 탭뷰 제스쳐 수정
- [x] 탭뷰 내부 뷰 수정
- [x] Day 계산 필요
- [x] 오버레이로 그라데이션 뷰 추가
- [ ] TabView 사이의 padding 값 조정
